spring.datasource.url=${MYSQL_URI:jdbc:mysql://localhost:3306/betting}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:root}
logging.level.root=info

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

smibet.scadenzamesistandard=1
smibet.pagamentostandard=10.0
smibet.trialPeriodStandard=2

server.port=8082

jwtSecret=6os7zy5DjYv7giTePxhz0X7L3sVGUDdBzmAwQNdDXZHUBty7ohjsBk4ZHSjVRFL4HIbyVs9AfrTfriDVFhN4FD55RUySQppD3ZrvJrQza3Ts4qmiAVIbEaSfo8kAyaQ2U74yaQPPlmTgoLUxyYv7cXLh7AElKFNSvl4udaKrlO2T3Iyg3NYPGuNhTUq0CpsAe0f9J0BwLXc1iCNemSmVT283MVZeyxAsbrQoDnF2SoSrWdyftx7TM9x11DYKjQ9Y


bot.baseurl=${URL_BOT:http://localhost:3000}
bot.esitoRichiesta=/esito
bot.broadcast=/api/sendBroadcast
bot.sendMessage=/sendMessage

#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=mgbetbackoffice@gmail.com
spring.mail.password=tttvkhzugopyandv

