#RICORDARSI DI IMPOSTARE LE VARIABILI D'AMBIENTE
spring.datasource.url=${MYSQL_URI:jdbc:mysql://localhost:3306/betting}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
server.port=8080

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=12
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

url-bot=${URL_BOT:http://localhost:3000}

server.servlet.context-path=/api

#Jwt
jwtSecret=6os7zy5DjYv7giTePxhz0X7L3sVGUDdBzmAwQNdDXZHUBty7ohjsBk4ZHSjVRFL4HIbyVs9AfrTfriDVFhN4FD55RUySQppD3ZrvJrQza3Ts4qmiAVIbEaSfo8kAyaQ2U74yaQPPlmTgoLUxyYv7cXLh7AElKFNSvl4udaKrlO2T3Iyg3NYPGuNhTUq0CpsAe0f9J0BwLXc1iCNemSmVT283MVZeyxAsbrQoDnF2SoSrWdyftx7TM9x11DYKjQ9Y
jwtExpiration=2592000000
